// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: elevatorService.proto

package grpc.elevatorService;

public interface ElevatorRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:elevatorService.ElevatorRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.elevatorService.Occupant occupant = 1;</code>
   */
  boolean hasOccupant();
  /**
   * <code>.elevatorService.Occupant occupant = 1;</code>
   */
  grpc.elevatorService.Occupant getOccupant();
  /**
   * <code>.elevatorService.Occupant occupant = 1;</code>
   */
  grpc.elevatorService.OccupantOrBuilder getOccupantOrBuilder();

  /**
   * <code>.elevatorService.Elevator elevator = 2;</code>
   */
  boolean hasElevator();
  /**
   * <code>.elevatorService.Elevator elevator = 2;</code>
   */
  grpc.elevatorService.Elevator getElevator();
  /**
   * <code>.elevatorService.Elevator elevator = 2;</code>
   */
  grpc.elevatorService.ElevatorOrBuilder getElevatorOrBuilder();

  /**
   * <code>int32 currentFloor = 3;</code>
   */
  int getCurrentFloor();

  /**
   * <code>repeated int32 destinationFloor = 4;</code>
   */
  java.util.List<java.lang.Integer> getDestinationFloorList();
  /**
   * <code>repeated int32 destinationFloor = 4;</code>
   */
  int getDestinationFloorCount();
  /**
   * <code>repeated int32 destinationFloor = 4;</code>
   */
  int getDestinationFloor(int index);
}
