// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: elevatorService.proto

package grpc.elevatorService;

public interface ElevatorResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:elevatorService.ElevatorResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string elevatorMessage = 1;</code>
   */
  java.lang.String getElevatorMessage();
  /**
   * <code>string elevatorMessage = 1;</code>
   */
  com.google.protobuf.ByteString
      getElevatorMessageBytes();

  /**
   * <code>int32 currentFloor = 2;</code>
   */
  int getCurrentFloor();

  /**
   * <code>int32 nextFloor = 3;</code>
   */
  int getNextFloor();
}
