// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: elevatorService.proto

package grpc.elevatorService;

public interface ElevatorOrBuilder extends
    // @@protoc_insertion_point(interface_extends:elevatorService.Elevator)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 id = 1;</code>
   */
  int getId();

  /**
   * <code>int32 currentFloor = 2;</code>
   */
  int getCurrentFloor();

  /**
   * <code>int32 destinationFLoor = 3;</code>
   */
  int getDestinationFLoor();

  /**
   * <code>int32 lowestFloor = 4;</code>
   */
  int getLowestFloor();

  /**
   * <code>int32 highestFloor = 5;</code>
   */
  int getHighestFloor();

  /**
   * <code>int32 capacityLimit = 6;</code>
   */
  int getCapacityLimit();

  /**
   * <code>int32 currentCapacity = 7;</code>
   */
  int getCurrentCapacity();

  /**
   * <code>bool isMoving = 8;</code>
   */
  boolean getIsMoving();

  /**
   * <code>.elevatorService.Elevator.travelDirection tDirection = 9;</code>
   */
  int getTDirectionValue();
  /**
   * <code>.elevatorService.Elevator.travelDirection tDirection = 9;</code>
   */
  grpc.elevatorService.Elevator.travelDirection getTDirection();
}
