// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: elevatorService.proto

package grpc.elevatorService;

/**
 * Protobuf type {@code elevatorService.ElevatorResponse}
 */
public  final class ElevatorResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:elevatorService.ElevatorResponse)
    ElevatorResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ElevatorResponse.newBuilder() to construct.
  private ElevatorResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ElevatorResponse() {
    elevatorMessage_ = "";
    currentFloor_ = 0;
    nextFloor_ = 0;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private ElevatorResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            elevatorMessage_ = s;
            break;
          }
          case 16: {

            currentFloor_ = input.readInt32();
            break;
          }
          case 24: {

            nextFloor_ = input.readInt32();
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return grpc.elevatorService.ElevatorServiceImpl.internal_static_elevatorService_ElevatorResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return grpc.elevatorService.ElevatorServiceImpl.internal_static_elevatorService_ElevatorResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            grpc.elevatorService.ElevatorResponse.class, grpc.elevatorService.ElevatorResponse.Builder.class);
  }

  public static final int ELEVATORMESSAGE_FIELD_NUMBER = 1;
  private volatile java.lang.Object elevatorMessage_;
  /**
   * <code>string elevatorMessage = 1;</code>
   */
  public java.lang.String getElevatorMessage() {
    java.lang.Object ref = elevatorMessage_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      elevatorMessage_ = s;
      return s;
    }
  }
  /**
   * <code>string elevatorMessage = 1;</code>
   */
  public com.google.protobuf.ByteString
      getElevatorMessageBytes() {
    java.lang.Object ref = elevatorMessage_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      elevatorMessage_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int CURRENTFLOOR_FIELD_NUMBER = 2;
  private int currentFloor_;
  /**
   * <code>int32 currentFloor = 2;</code>
   */
  public int getCurrentFloor() {
    return currentFloor_;
  }

  public static final int NEXTFLOOR_FIELD_NUMBER = 3;
  private int nextFloor_;
  /**
   * <code>int32 nextFloor = 3;</code>
   */
  public int getNextFloor() {
    return nextFloor_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getElevatorMessageBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, elevatorMessage_);
    }
    if (currentFloor_ != 0) {
      output.writeInt32(2, currentFloor_);
    }
    if (nextFloor_ != 0) {
      output.writeInt32(3, nextFloor_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getElevatorMessageBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, elevatorMessage_);
    }
    if (currentFloor_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(2, currentFloor_);
    }
    if (nextFloor_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(3, nextFloor_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof grpc.elevatorService.ElevatorResponse)) {
      return super.equals(obj);
    }
    grpc.elevatorService.ElevatorResponse other = (grpc.elevatorService.ElevatorResponse) obj;

    boolean result = true;
    result = result && getElevatorMessage()
        .equals(other.getElevatorMessage());
    result = result && (getCurrentFloor()
        == other.getCurrentFloor());
    result = result && (getNextFloor()
        == other.getNextFloor());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ELEVATORMESSAGE_FIELD_NUMBER;
    hash = (53 * hash) + getElevatorMessage().hashCode();
    hash = (37 * hash) + CURRENTFLOOR_FIELD_NUMBER;
    hash = (53 * hash) + getCurrentFloor();
    hash = (37 * hash) + NEXTFLOOR_FIELD_NUMBER;
    hash = (53 * hash) + getNextFloor();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static grpc.elevatorService.ElevatorResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static grpc.elevatorService.ElevatorResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static grpc.elevatorService.ElevatorResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static grpc.elevatorService.ElevatorResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static grpc.elevatorService.ElevatorResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static grpc.elevatorService.ElevatorResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static grpc.elevatorService.ElevatorResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static grpc.elevatorService.ElevatorResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static grpc.elevatorService.ElevatorResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static grpc.elevatorService.ElevatorResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static grpc.elevatorService.ElevatorResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static grpc.elevatorService.ElevatorResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(grpc.elevatorService.ElevatorResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code elevatorService.ElevatorResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:elevatorService.ElevatorResponse)
      grpc.elevatorService.ElevatorResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return grpc.elevatorService.ElevatorServiceImpl.internal_static_elevatorService_ElevatorResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return grpc.elevatorService.ElevatorServiceImpl.internal_static_elevatorService_ElevatorResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              grpc.elevatorService.ElevatorResponse.class, grpc.elevatorService.ElevatorResponse.Builder.class);
    }

    // Construct using grpc.elevatorService.ElevatorResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      elevatorMessage_ = "";

      currentFloor_ = 0;

      nextFloor_ = 0;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return grpc.elevatorService.ElevatorServiceImpl.internal_static_elevatorService_ElevatorResponse_descriptor;
    }

    @java.lang.Override
    public grpc.elevatorService.ElevatorResponse getDefaultInstanceForType() {
      return grpc.elevatorService.ElevatorResponse.getDefaultInstance();
    }

    @java.lang.Override
    public grpc.elevatorService.ElevatorResponse build() {
      grpc.elevatorService.ElevatorResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public grpc.elevatorService.ElevatorResponse buildPartial() {
      grpc.elevatorService.ElevatorResponse result = new grpc.elevatorService.ElevatorResponse(this);
      result.elevatorMessage_ = elevatorMessage_;
      result.currentFloor_ = currentFloor_;
      result.nextFloor_ = nextFloor_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof grpc.elevatorService.ElevatorResponse) {
        return mergeFrom((grpc.elevatorService.ElevatorResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(grpc.elevatorService.ElevatorResponse other) {
      if (other == grpc.elevatorService.ElevatorResponse.getDefaultInstance()) return this;
      if (!other.getElevatorMessage().isEmpty()) {
        elevatorMessage_ = other.elevatorMessage_;
        onChanged();
      }
      if (other.getCurrentFloor() != 0) {
        setCurrentFloor(other.getCurrentFloor());
      }
      if (other.getNextFloor() != 0) {
        setNextFloor(other.getNextFloor());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      grpc.elevatorService.ElevatorResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (grpc.elevatorService.ElevatorResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object elevatorMessage_ = "";
    /**
     * <code>string elevatorMessage = 1;</code>
     */
    public java.lang.String getElevatorMessage() {
      java.lang.Object ref = elevatorMessage_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        elevatorMessage_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string elevatorMessage = 1;</code>
     */
    public com.google.protobuf.ByteString
        getElevatorMessageBytes() {
      java.lang.Object ref = elevatorMessage_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        elevatorMessage_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string elevatorMessage = 1;</code>
     */
    public Builder setElevatorMessage(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      elevatorMessage_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string elevatorMessage = 1;</code>
     */
    public Builder clearElevatorMessage() {
      
      elevatorMessage_ = getDefaultInstance().getElevatorMessage();
      onChanged();
      return this;
    }
    /**
     * <code>string elevatorMessage = 1;</code>
     */
    public Builder setElevatorMessageBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      elevatorMessage_ = value;
      onChanged();
      return this;
    }

    private int currentFloor_ ;
    /**
     * <code>int32 currentFloor = 2;</code>
     */
    public int getCurrentFloor() {
      return currentFloor_;
    }
    /**
     * <code>int32 currentFloor = 2;</code>
     */
    public Builder setCurrentFloor(int value) {
      
      currentFloor_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 currentFloor = 2;</code>
     */
    public Builder clearCurrentFloor() {
      
      currentFloor_ = 0;
      onChanged();
      return this;
    }

    private int nextFloor_ ;
    /**
     * <code>int32 nextFloor = 3;</code>
     */
    public int getNextFloor() {
      return nextFloor_;
    }
    /**
     * <code>int32 nextFloor = 3;</code>
     */
    public Builder setNextFloor(int value) {
      
      nextFloor_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 nextFloor = 3;</code>
     */
    public Builder clearNextFloor() {
      
      nextFloor_ = 0;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:elevatorService.ElevatorResponse)
  }

  // @@protoc_insertion_point(class_scope:elevatorService.ElevatorResponse)
  private static final grpc.elevatorService.ElevatorResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new grpc.elevatorService.ElevatorResponse();
  }

  public static grpc.elevatorService.ElevatorResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ElevatorResponse>
      PARSER = new com.google.protobuf.AbstractParser<ElevatorResponse>() {
    @java.lang.Override
    public ElevatorResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new ElevatorResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ElevatorResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ElevatorResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public grpc.elevatorService.ElevatorResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

