// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: elevatorService.proto

package grpc.elevatorService;

public final class ElevatorServiceImpl {
  private ElevatorServiceImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_elevatorService_Occupant_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_elevatorService_Occupant_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_elevatorService_Elevator_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_elevatorService_Elevator_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_elevatorService_ElevatorRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_elevatorService_ElevatorRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_elevatorService_ElevatorResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_elevatorService_ElevatorResponse_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_elevatorService_OccupantDatabase_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_elevatorService_OccupantDatabase_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\025elevatorService.proto\022\017elevatorService" +
      "\"b\n\010Occupant\022\n\n\002id\030\001 \001(\005\022\014\n\004name\030\002 \001(\t\022\021" +
      "\n\troomFloor\030\003 \001(\005\022\022\n\nroomNumber\030\004 \001(\005\022\025\n" +
      "\raccessToFloor\030\005 \003(\005\"\227\002\n\010Elevator\022\n\n\002id\030" +
      "\001 \001(\005\022\024\n\014currentFloor\030\002 \001(\005\022\030\n\020destinati" +
      "onFLoor\030\003 \001(\005\022\023\n\013lowestFloor\030\004 \001(\005\022\024\n\014hi" +
      "ghestFloor\030\005 \001(\005\022\025\n\rcapacityLimit\030\006 \001(\005\022" +
      "\027\n\017currentCapacity\030\007 \001(\005\022\020\n\010isMoving\030\010 \001" +
      "(\010\022=\n\ntDirection\030\t \001(\0162).elevatorService" +
      ".Elevator.travelDirection\"#\n\017travelDirec" +
      "tion\022\006\n\002UP\020\000\022\010\n\004DOWN\020\001\"\233\001\n\017ElevatorReque" +
      "st\022+\n\010occupant\030\001 \001(\0132\031.elevatorService.O" +
      "ccupant\022+\n\010elevator\030\002 \001(\0132\031.elevatorServ" +
      "ice.Elevator\022\024\n\014currentFloor\030\003 \001(\005\022\030\n\020de" +
      "stinationFloor\030\004 \003(\005\"T\n\020ElevatorResponse" +
      "\022\027\n\017elevatorMessage\030\001 \001(\t\022\024\n\014currentFloo" +
      "r\030\002 \001(\005\022\021\n\tnextFloor\030\003 \001(\005\"?\n\020OccupantDa" +
      "tabase\022+\n\010occupant\030\001 \003(\0132\031.elevatorServi" +
      "ce.Occupant2\274\001\n\010elevator\022Y\n\014moveElevator" +
      "\022 .elevatorService.ElevatorRequest\032!.ele" +
      "vatorService.ElevatorResponse\"\000(\0010\001\022U\n\023r" +
      "eturnToGroundFloor\022\031.elevatorService.Ele" +
      "vator\032!.elevatorService.ElevatorResponse" +
      "\"\000B-\n\024grpc.elevatorServiceB\023ElevatorServ" +
      "iceImplP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_elevatorService_Occupant_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_elevatorService_Occupant_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_elevatorService_Occupant_descriptor,
        new java.lang.String[] { "Id", "Name", "RoomFloor", "RoomNumber", "AccessToFloor", });
    internal_static_elevatorService_Elevator_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_elevatorService_Elevator_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_elevatorService_Elevator_descriptor,
        new java.lang.String[] { "Id", "CurrentFloor", "DestinationFLoor", "LowestFloor", "HighestFloor", "CapacityLimit", "CurrentCapacity", "IsMoving", "TDirection", });
    internal_static_elevatorService_ElevatorRequest_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_elevatorService_ElevatorRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_elevatorService_ElevatorRequest_descriptor,
        new java.lang.String[] { "Occupant", "Elevator", "CurrentFloor", "DestinationFloor", });
    internal_static_elevatorService_ElevatorResponse_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_elevatorService_ElevatorResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_elevatorService_ElevatorResponse_descriptor,
        new java.lang.String[] { "ElevatorMessage", "CurrentFloor", "NextFloor", });
    internal_static_elevatorService_OccupantDatabase_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_elevatorService_OccupantDatabase_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_elevatorService_OccupantDatabase_descriptor,
        new java.lang.String[] { "Occupant", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
