// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: elevatorService.proto

package grpc.elevatorService;

/**
 * Protobuf type {@code elevatorService.ElevatorRequest}
 */
public  final class ElevatorRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:elevatorService.ElevatorRequest)
    ElevatorRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use ElevatorRequest.newBuilder() to construct.
  private ElevatorRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private ElevatorRequest() {
    currentFloor_ = 0;
    destinationFloor_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private ElevatorRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            grpc.elevatorService.Occupant.Builder subBuilder = null;
            if (occupant_ != null) {
              subBuilder = occupant_.toBuilder();
            }
            occupant_ = input.readMessage(grpc.elevatorService.Occupant.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(occupant_);
              occupant_ = subBuilder.buildPartial();
            }

            break;
          }
          case 18: {
            grpc.elevatorService.Elevator.Builder subBuilder = null;
            if (elevator_ != null) {
              subBuilder = elevator_.toBuilder();
            }
            elevator_ = input.readMessage(grpc.elevatorService.Elevator.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(elevator_);
              elevator_ = subBuilder.buildPartial();
            }

            break;
          }
          case 24: {

            currentFloor_ = input.readInt32();
            break;
          }
          case 32: {
            if (!((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
              destinationFloor_ = new java.util.ArrayList<java.lang.Integer>();
              mutable_bitField0_ |= 0x00000008;
            }
            destinationFloor_.add(input.readInt32());
            break;
          }
          case 34: {
            int length = input.readRawVarint32();
            int limit = input.pushLimit(length);
            if (!((mutable_bitField0_ & 0x00000008) == 0x00000008) && input.getBytesUntilLimit() > 0) {
              destinationFloor_ = new java.util.ArrayList<java.lang.Integer>();
              mutable_bitField0_ |= 0x00000008;
            }
            while (input.getBytesUntilLimit() > 0) {
              destinationFloor_.add(input.readInt32());
            }
            input.popLimit(limit);
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
        destinationFloor_ = java.util.Collections.unmodifiableList(destinationFloor_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return grpc.elevatorService.ElevatorServiceImpl.internal_static_elevatorService_ElevatorRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return grpc.elevatorService.ElevatorServiceImpl.internal_static_elevatorService_ElevatorRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            grpc.elevatorService.ElevatorRequest.class, grpc.elevatorService.ElevatorRequest.Builder.class);
  }

  private int bitField0_;
  public static final int OCCUPANT_FIELD_NUMBER = 1;
  private grpc.elevatorService.Occupant occupant_;
  /**
   * <code>.elevatorService.Occupant occupant = 1;</code>
   */
  public boolean hasOccupant() {
    return occupant_ != null;
  }
  /**
   * <code>.elevatorService.Occupant occupant = 1;</code>
   */
  public grpc.elevatorService.Occupant getOccupant() {
    return occupant_ == null ? grpc.elevatorService.Occupant.getDefaultInstance() : occupant_;
  }
  /**
   * <code>.elevatorService.Occupant occupant = 1;</code>
   */
  public grpc.elevatorService.OccupantOrBuilder getOccupantOrBuilder() {
    return getOccupant();
  }

  public static final int ELEVATOR_FIELD_NUMBER = 2;
  private grpc.elevatorService.Elevator elevator_;
  /**
   * <code>.elevatorService.Elevator elevator = 2;</code>
   */
  public boolean hasElevator() {
    return elevator_ != null;
  }
  /**
   * <code>.elevatorService.Elevator elevator = 2;</code>
   */
  public grpc.elevatorService.Elevator getElevator() {
    return elevator_ == null ? grpc.elevatorService.Elevator.getDefaultInstance() : elevator_;
  }
  /**
   * <code>.elevatorService.Elevator elevator = 2;</code>
   */
  public grpc.elevatorService.ElevatorOrBuilder getElevatorOrBuilder() {
    return getElevator();
  }

  public static final int CURRENTFLOOR_FIELD_NUMBER = 3;
  private int currentFloor_;
  /**
   * <code>int32 currentFloor = 3;</code>
   */
  public int getCurrentFloor() {
    return currentFloor_;
  }

  public static final int DESTINATIONFLOOR_FIELD_NUMBER = 4;
  private java.util.List<java.lang.Integer> destinationFloor_;
  /**
   * <code>repeated int32 destinationFloor = 4;</code>
   */
  public java.util.List<java.lang.Integer>
      getDestinationFloorList() {
    return destinationFloor_;
  }
  /**
   * <code>repeated int32 destinationFloor = 4;</code>
   */
  public int getDestinationFloorCount() {
    return destinationFloor_.size();
  }
  /**
   * <code>repeated int32 destinationFloor = 4;</code>
   */
  public int getDestinationFloor(int index) {
    return destinationFloor_.get(index);
  }
  private int destinationFloorMemoizedSerializedSize = -1;

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    getSerializedSize();
    if (occupant_ != null) {
      output.writeMessage(1, getOccupant());
    }
    if (elevator_ != null) {
      output.writeMessage(2, getElevator());
    }
    if (currentFloor_ != 0) {
      output.writeInt32(3, currentFloor_);
    }
    if (getDestinationFloorList().size() > 0) {
      output.writeUInt32NoTag(34);
      output.writeUInt32NoTag(destinationFloorMemoizedSerializedSize);
    }
    for (int i = 0; i < destinationFloor_.size(); i++) {
      output.writeInt32NoTag(destinationFloor_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (occupant_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getOccupant());
    }
    if (elevator_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getElevator());
    }
    if (currentFloor_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(3, currentFloor_);
    }
    {
      int dataSize = 0;
      for (int i = 0; i < destinationFloor_.size(); i++) {
        dataSize += com.google.protobuf.CodedOutputStream
          .computeInt32SizeNoTag(destinationFloor_.get(i));
      }
      size += dataSize;
      if (!getDestinationFloorList().isEmpty()) {
        size += 1;
        size += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(dataSize);
      }
      destinationFloorMemoizedSerializedSize = dataSize;
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof grpc.elevatorService.ElevatorRequest)) {
      return super.equals(obj);
    }
    grpc.elevatorService.ElevatorRequest other = (grpc.elevatorService.ElevatorRequest) obj;

    boolean result = true;
    result = result && (hasOccupant() == other.hasOccupant());
    if (hasOccupant()) {
      result = result && getOccupant()
          .equals(other.getOccupant());
    }
    result = result && (hasElevator() == other.hasElevator());
    if (hasElevator()) {
      result = result && getElevator()
          .equals(other.getElevator());
    }
    result = result && (getCurrentFloor()
        == other.getCurrentFloor());
    result = result && getDestinationFloorList()
        .equals(other.getDestinationFloorList());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasOccupant()) {
      hash = (37 * hash) + OCCUPANT_FIELD_NUMBER;
      hash = (53 * hash) + getOccupant().hashCode();
    }
    if (hasElevator()) {
      hash = (37 * hash) + ELEVATOR_FIELD_NUMBER;
      hash = (53 * hash) + getElevator().hashCode();
    }
    hash = (37 * hash) + CURRENTFLOOR_FIELD_NUMBER;
    hash = (53 * hash) + getCurrentFloor();
    if (getDestinationFloorCount() > 0) {
      hash = (37 * hash) + DESTINATIONFLOOR_FIELD_NUMBER;
      hash = (53 * hash) + getDestinationFloorList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static grpc.elevatorService.ElevatorRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static grpc.elevatorService.ElevatorRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static grpc.elevatorService.ElevatorRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static grpc.elevatorService.ElevatorRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static grpc.elevatorService.ElevatorRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static grpc.elevatorService.ElevatorRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static grpc.elevatorService.ElevatorRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static grpc.elevatorService.ElevatorRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static grpc.elevatorService.ElevatorRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static grpc.elevatorService.ElevatorRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static grpc.elevatorService.ElevatorRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static grpc.elevatorService.ElevatorRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(grpc.elevatorService.ElevatorRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code elevatorService.ElevatorRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:elevatorService.ElevatorRequest)
      grpc.elevatorService.ElevatorRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return grpc.elevatorService.ElevatorServiceImpl.internal_static_elevatorService_ElevatorRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return grpc.elevatorService.ElevatorServiceImpl.internal_static_elevatorService_ElevatorRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              grpc.elevatorService.ElevatorRequest.class, grpc.elevatorService.ElevatorRequest.Builder.class);
    }

    // Construct using grpc.elevatorService.ElevatorRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (occupantBuilder_ == null) {
        occupant_ = null;
      } else {
        occupant_ = null;
        occupantBuilder_ = null;
      }
      if (elevatorBuilder_ == null) {
        elevator_ = null;
      } else {
        elevator_ = null;
        elevatorBuilder_ = null;
      }
      currentFloor_ = 0;

      destinationFloor_ = java.util.Collections.emptyList();
      bitField0_ = (bitField0_ & ~0x00000008);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return grpc.elevatorService.ElevatorServiceImpl.internal_static_elevatorService_ElevatorRequest_descriptor;
    }

    @java.lang.Override
    public grpc.elevatorService.ElevatorRequest getDefaultInstanceForType() {
      return grpc.elevatorService.ElevatorRequest.getDefaultInstance();
    }

    @java.lang.Override
    public grpc.elevatorService.ElevatorRequest build() {
      grpc.elevatorService.ElevatorRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public grpc.elevatorService.ElevatorRequest buildPartial() {
      grpc.elevatorService.ElevatorRequest result = new grpc.elevatorService.ElevatorRequest(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (occupantBuilder_ == null) {
        result.occupant_ = occupant_;
      } else {
        result.occupant_ = occupantBuilder_.build();
      }
      if (elevatorBuilder_ == null) {
        result.elevator_ = elevator_;
      } else {
        result.elevator_ = elevatorBuilder_.build();
      }
      result.currentFloor_ = currentFloor_;
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        destinationFloor_ = java.util.Collections.unmodifiableList(destinationFloor_);
        bitField0_ = (bitField0_ & ~0x00000008);
      }
      result.destinationFloor_ = destinationFloor_;
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof grpc.elevatorService.ElevatorRequest) {
        return mergeFrom((grpc.elevatorService.ElevatorRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(grpc.elevatorService.ElevatorRequest other) {
      if (other == grpc.elevatorService.ElevatorRequest.getDefaultInstance()) return this;
      if (other.hasOccupant()) {
        mergeOccupant(other.getOccupant());
      }
      if (other.hasElevator()) {
        mergeElevator(other.getElevator());
      }
      if (other.getCurrentFloor() != 0) {
        setCurrentFloor(other.getCurrentFloor());
      }
      if (!other.destinationFloor_.isEmpty()) {
        if (destinationFloor_.isEmpty()) {
          destinationFloor_ = other.destinationFloor_;
          bitField0_ = (bitField0_ & ~0x00000008);
        } else {
          ensureDestinationFloorIsMutable();
          destinationFloor_.addAll(other.destinationFloor_);
        }
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      grpc.elevatorService.ElevatorRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (grpc.elevatorService.ElevatorRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private grpc.elevatorService.Occupant occupant_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        grpc.elevatorService.Occupant, grpc.elevatorService.Occupant.Builder, grpc.elevatorService.OccupantOrBuilder> occupantBuilder_;
    /**
     * <code>.elevatorService.Occupant occupant = 1;</code>
     */
    public boolean hasOccupant() {
      return occupantBuilder_ != null || occupant_ != null;
    }
    /**
     * <code>.elevatorService.Occupant occupant = 1;</code>
     */
    public grpc.elevatorService.Occupant getOccupant() {
      if (occupantBuilder_ == null) {
        return occupant_ == null ? grpc.elevatorService.Occupant.getDefaultInstance() : occupant_;
      } else {
        return occupantBuilder_.getMessage();
      }
    }
    /**
     * <code>.elevatorService.Occupant occupant = 1;</code>
     */
    public Builder setOccupant(grpc.elevatorService.Occupant value) {
      if (occupantBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        occupant_ = value;
        onChanged();
      } else {
        occupantBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.elevatorService.Occupant occupant = 1;</code>
     */
    public Builder setOccupant(
        grpc.elevatorService.Occupant.Builder builderForValue) {
      if (occupantBuilder_ == null) {
        occupant_ = builderForValue.build();
        onChanged();
      } else {
        occupantBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.elevatorService.Occupant occupant = 1;</code>
     */
    public Builder mergeOccupant(grpc.elevatorService.Occupant value) {
      if (occupantBuilder_ == null) {
        if (occupant_ != null) {
          occupant_ =
            grpc.elevatorService.Occupant.newBuilder(occupant_).mergeFrom(value).buildPartial();
        } else {
          occupant_ = value;
        }
        onChanged();
      } else {
        occupantBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.elevatorService.Occupant occupant = 1;</code>
     */
    public Builder clearOccupant() {
      if (occupantBuilder_ == null) {
        occupant_ = null;
        onChanged();
      } else {
        occupant_ = null;
        occupantBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.elevatorService.Occupant occupant = 1;</code>
     */
    public grpc.elevatorService.Occupant.Builder getOccupantBuilder() {
      
      onChanged();
      return getOccupantFieldBuilder().getBuilder();
    }
    /**
     * <code>.elevatorService.Occupant occupant = 1;</code>
     */
    public grpc.elevatorService.OccupantOrBuilder getOccupantOrBuilder() {
      if (occupantBuilder_ != null) {
        return occupantBuilder_.getMessageOrBuilder();
      } else {
        return occupant_ == null ?
            grpc.elevatorService.Occupant.getDefaultInstance() : occupant_;
      }
    }
    /**
     * <code>.elevatorService.Occupant occupant = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        grpc.elevatorService.Occupant, grpc.elevatorService.Occupant.Builder, grpc.elevatorService.OccupantOrBuilder> 
        getOccupantFieldBuilder() {
      if (occupantBuilder_ == null) {
        occupantBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            grpc.elevatorService.Occupant, grpc.elevatorService.Occupant.Builder, grpc.elevatorService.OccupantOrBuilder>(
                getOccupant(),
                getParentForChildren(),
                isClean());
        occupant_ = null;
      }
      return occupantBuilder_;
    }

    private grpc.elevatorService.Elevator elevator_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        grpc.elevatorService.Elevator, grpc.elevatorService.Elevator.Builder, grpc.elevatorService.ElevatorOrBuilder> elevatorBuilder_;
    /**
     * <code>.elevatorService.Elevator elevator = 2;</code>
     */
    public boolean hasElevator() {
      return elevatorBuilder_ != null || elevator_ != null;
    }
    /**
     * <code>.elevatorService.Elevator elevator = 2;</code>
     */
    public grpc.elevatorService.Elevator getElevator() {
      if (elevatorBuilder_ == null) {
        return elevator_ == null ? grpc.elevatorService.Elevator.getDefaultInstance() : elevator_;
      } else {
        return elevatorBuilder_.getMessage();
      }
    }
    /**
     * <code>.elevatorService.Elevator elevator = 2;</code>
     */
    public Builder setElevator(grpc.elevatorService.Elevator value) {
      if (elevatorBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        elevator_ = value;
        onChanged();
      } else {
        elevatorBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.elevatorService.Elevator elevator = 2;</code>
     */
    public Builder setElevator(
        grpc.elevatorService.Elevator.Builder builderForValue) {
      if (elevatorBuilder_ == null) {
        elevator_ = builderForValue.build();
        onChanged();
      } else {
        elevatorBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.elevatorService.Elevator elevator = 2;</code>
     */
    public Builder mergeElevator(grpc.elevatorService.Elevator value) {
      if (elevatorBuilder_ == null) {
        if (elevator_ != null) {
          elevator_ =
            grpc.elevatorService.Elevator.newBuilder(elevator_).mergeFrom(value).buildPartial();
        } else {
          elevator_ = value;
        }
        onChanged();
      } else {
        elevatorBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.elevatorService.Elevator elevator = 2;</code>
     */
    public Builder clearElevator() {
      if (elevatorBuilder_ == null) {
        elevator_ = null;
        onChanged();
      } else {
        elevator_ = null;
        elevatorBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.elevatorService.Elevator elevator = 2;</code>
     */
    public grpc.elevatorService.Elevator.Builder getElevatorBuilder() {
      
      onChanged();
      return getElevatorFieldBuilder().getBuilder();
    }
    /**
     * <code>.elevatorService.Elevator elevator = 2;</code>
     */
    public grpc.elevatorService.ElevatorOrBuilder getElevatorOrBuilder() {
      if (elevatorBuilder_ != null) {
        return elevatorBuilder_.getMessageOrBuilder();
      } else {
        return elevator_ == null ?
            grpc.elevatorService.Elevator.getDefaultInstance() : elevator_;
      }
    }
    /**
     * <code>.elevatorService.Elevator elevator = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        grpc.elevatorService.Elevator, grpc.elevatorService.Elevator.Builder, grpc.elevatorService.ElevatorOrBuilder> 
        getElevatorFieldBuilder() {
      if (elevatorBuilder_ == null) {
        elevatorBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            grpc.elevatorService.Elevator, grpc.elevatorService.Elevator.Builder, grpc.elevatorService.ElevatorOrBuilder>(
                getElevator(),
                getParentForChildren(),
                isClean());
        elevator_ = null;
      }
      return elevatorBuilder_;
    }

    private int currentFloor_ ;
    /**
     * <code>int32 currentFloor = 3;</code>
     */
    public int getCurrentFloor() {
      return currentFloor_;
    }
    /**
     * <code>int32 currentFloor = 3;</code>
     */
    public Builder setCurrentFloor(int value) {
      
      currentFloor_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 currentFloor = 3;</code>
     */
    public Builder clearCurrentFloor() {
      
      currentFloor_ = 0;
      onChanged();
      return this;
    }

    private java.util.List<java.lang.Integer> destinationFloor_ = java.util.Collections.emptyList();
    private void ensureDestinationFloorIsMutable() {
      if (!((bitField0_ & 0x00000008) == 0x00000008)) {
        destinationFloor_ = new java.util.ArrayList<java.lang.Integer>(destinationFloor_);
        bitField0_ |= 0x00000008;
       }
    }
    /**
     * <code>repeated int32 destinationFloor = 4;</code>
     */
    public java.util.List<java.lang.Integer>
        getDestinationFloorList() {
      return java.util.Collections.unmodifiableList(destinationFloor_);
    }
    /**
     * <code>repeated int32 destinationFloor = 4;</code>
     */
    public int getDestinationFloorCount() {
      return destinationFloor_.size();
    }
    /**
     * <code>repeated int32 destinationFloor = 4;</code>
     */
    public int getDestinationFloor(int index) {
      return destinationFloor_.get(index);
    }
    /**
     * <code>repeated int32 destinationFloor = 4;</code>
     */
    public Builder setDestinationFloor(
        int index, int value) {
      ensureDestinationFloorIsMutable();
      destinationFloor_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated int32 destinationFloor = 4;</code>
     */
    public Builder addDestinationFloor(int value) {
      ensureDestinationFloorIsMutable();
      destinationFloor_.add(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated int32 destinationFloor = 4;</code>
     */
    public Builder addAllDestinationFloor(
        java.lang.Iterable<? extends java.lang.Integer> values) {
      ensureDestinationFloorIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, destinationFloor_);
      onChanged();
      return this;
    }
    /**
     * <code>repeated int32 destinationFloor = 4;</code>
     */
    public Builder clearDestinationFloor() {
      destinationFloor_ = java.util.Collections.emptyList();
      bitField0_ = (bitField0_ & ~0x00000008);
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:elevatorService.ElevatorRequest)
  }

  // @@protoc_insertion_point(class_scope:elevatorService.ElevatorRequest)
  private static final grpc.elevatorService.ElevatorRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new grpc.elevatorService.ElevatorRequest();
  }

  public static grpc.elevatorService.ElevatorRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ElevatorRequest>
      PARSER = new com.google.protobuf.AbstractParser<ElevatorRequest>() {
    @java.lang.Override
    public ElevatorRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new ElevatorRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<ElevatorRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ElevatorRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public grpc.elevatorService.ElevatorRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

