// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: elevatorService.proto

package grpc.elevatorService;

/**
 * Protobuf type {@code elevatorService.OccupantDatabase}
 */
public  final class OccupantDatabase extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:elevatorService.OccupantDatabase)
    OccupantDatabaseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use OccupantDatabase.newBuilder() to construct.
  private OccupantDatabase(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private OccupantDatabase() {
    occupant_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private OccupantDatabase(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
              occupant_ = new java.util.ArrayList<grpc.elevatorService.Occupant>();
              mutable_bitField0_ |= 0x00000001;
            }
            occupant_.add(
                input.readMessage(grpc.elevatorService.Occupant.parser(), extensionRegistry));
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
        occupant_ = java.util.Collections.unmodifiableList(occupant_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return grpc.elevatorService.ElevatorServiceImpl.internal_static_elevatorService_OccupantDatabase_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return grpc.elevatorService.ElevatorServiceImpl.internal_static_elevatorService_OccupantDatabase_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            grpc.elevatorService.OccupantDatabase.class, grpc.elevatorService.OccupantDatabase.Builder.class);
  }

  public static final int OCCUPANT_FIELD_NUMBER = 1;
  private java.util.List<grpc.elevatorService.Occupant> occupant_;
  /**
   * <code>repeated .elevatorService.Occupant occupant = 1;</code>
   */
  public java.util.List<grpc.elevatorService.Occupant> getOccupantList() {
    return occupant_;
  }
  /**
   * <code>repeated .elevatorService.Occupant occupant = 1;</code>
   */
  public java.util.List<? extends grpc.elevatorService.OccupantOrBuilder> 
      getOccupantOrBuilderList() {
    return occupant_;
  }
  /**
   * <code>repeated .elevatorService.Occupant occupant = 1;</code>
   */
  public int getOccupantCount() {
    return occupant_.size();
  }
  /**
   * <code>repeated .elevatorService.Occupant occupant = 1;</code>
   */
  public grpc.elevatorService.Occupant getOccupant(int index) {
    return occupant_.get(index);
  }
  /**
   * <code>repeated .elevatorService.Occupant occupant = 1;</code>
   */
  public grpc.elevatorService.OccupantOrBuilder getOccupantOrBuilder(
      int index) {
    return occupant_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < occupant_.size(); i++) {
      output.writeMessage(1, occupant_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < occupant_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, occupant_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof grpc.elevatorService.OccupantDatabase)) {
      return super.equals(obj);
    }
    grpc.elevatorService.OccupantDatabase other = (grpc.elevatorService.OccupantDatabase) obj;

    boolean result = true;
    result = result && getOccupantList()
        .equals(other.getOccupantList());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getOccupantCount() > 0) {
      hash = (37 * hash) + OCCUPANT_FIELD_NUMBER;
      hash = (53 * hash) + getOccupantList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static grpc.elevatorService.OccupantDatabase parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static grpc.elevatorService.OccupantDatabase parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static grpc.elevatorService.OccupantDatabase parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static grpc.elevatorService.OccupantDatabase parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static grpc.elevatorService.OccupantDatabase parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static grpc.elevatorService.OccupantDatabase parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static grpc.elevatorService.OccupantDatabase parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static grpc.elevatorService.OccupantDatabase parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static grpc.elevatorService.OccupantDatabase parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static grpc.elevatorService.OccupantDatabase parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static grpc.elevatorService.OccupantDatabase parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static grpc.elevatorService.OccupantDatabase parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(grpc.elevatorService.OccupantDatabase prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code elevatorService.OccupantDatabase}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:elevatorService.OccupantDatabase)
      grpc.elevatorService.OccupantDatabaseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return grpc.elevatorService.ElevatorServiceImpl.internal_static_elevatorService_OccupantDatabase_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return grpc.elevatorService.ElevatorServiceImpl.internal_static_elevatorService_OccupantDatabase_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              grpc.elevatorService.OccupantDatabase.class, grpc.elevatorService.OccupantDatabase.Builder.class);
    }

    // Construct using grpc.elevatorService.OccupantDatabase.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getOccupantFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (occupantBuilder_ == null) {
        occupant_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        occupantBuilder_.clear();
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return grpc.elevatorService.ElevatorServiceImpl.internal_static_elevatorService_OccupantDatabase_descriptor;
    }

    @java.lang.Override
    public grpc.elevatorService.OccupantDatabase getDefaultInstanceForType() {
      return grpc.elevatorService.OccupantDatabase.getDefaultInstance();
    }

    @java.lang.Override
    public grpc.elevatorService.OccupantDatabase build() {
      grpc.elevatorService.OccupantDatabase result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public grpc.elevatorService.OccupantDatabase buildPartial() {
      grpc.elevatorService.OccupantDatabase result = new grpc.elevatorService.OccupantDatabase(this);
      int from_bitField0_ = bitField0_;
      if (occupantBuilder_ == null) {
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          occupant_ = java.util.Collections.unmodifiableList(occupant_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.occupant_ = occupant_;
      } else {
        result.occupant_ = occupantBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof grpc.elevatorService.OccupantDatabase) {
        return mergeFrom((grpc.elevatorService.OccupantDatabase)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(grpc.elevatorService.OccupantDatabase other) {
      if (other == grpc.elevatorService.OccupantDatabase.getDefaultInstance()) return this;
      if (occupantBuilder_ == null) {
        if (!other.occupant_.isEmpty()) {
          if (occupant_.isEmpty()) {
            occupant_ = other.occupant_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureOccupantIsMutable();
            occupant_.addAll(other.occupant_);
          }
          onChanged();
        }
      } else {
        if (!other.occupant_.isEmpty()) {
          if (occupantBuilder_.isEmpty()) {
            occupantBuilder_.dispose();
            occupantBuilder_ = null;
            occupant_ = other.occupant_;
            bitField0_ = (bitField0_ & ~0x00000001);
            occupantBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getOccupantFieldBuilder() : null;
          } else {
            occupantBuilder_.addAllMessages(other.occupant_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      grpc.elevatorService.OccupantDatabase parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (grpc.elevatorService.OccupantDatabase) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<grpc.elevatorService.Occupant> occupant_ =
      java.util.Collections.emptyList();
    private void ensureOccupantIsMutable() {
      if (!((bitField0_ & 0x00000001) == 0x00000001)) {
        occupant_ = new java.util.ArrayList<grpc.elevatorService.Occupant>(occupant_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        grpc.elevatorService.Occupant, grpc.elevatorService.Occupant.Builder, grpc.elevatorService.OccupantOrBuilder> occupantBuilder_;

    /**
     * <code>repeated .elevatorService.Occupant occupant = 1;</code>
     */
    public java.util.List<grpc.elevatorService.Occupant> getOccupantList() {
      if (occupantBuilder_ == null) {
        return java.util.Collections.unmodifiableList(occupant_);
      } else {
        return occupantBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .elevatorService.Occupant occupant = 1;</code>
     */
    public int getOccupantCount() {
      if (occupantBuilder_ == null) {
        return occupant_.size();
      } else {
        return occupantBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .elevatorService.Occupant occupant = 1;</code>
     */
    public grpc.elevatorService.Occupant getOccupant(int index) {
      if (occupantBuilder_ == null) {
        return occupant_.get(index);
      } else {
        return occupantBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .elevatorService.Occupant occupant = 1;</code>
     */
    public Builder setOccupant(
        int index, grpc.elevatorService.Occupant value) {
      if (occupantBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureOccupantIsMutable();
        occupant_.set(index, value);
        onChanged();
      } else {
        occupantBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .elevatorService.Occupant occupant = 1;</code>
     */
    public Builder setOccupant(
        int index, grpc.elevatorService.Occupant.Builder builderForValue) {
      if (occupantBuilder_ == null) {
        ensureOccupantIsMutable();
        occupant_.set(index, builderForValue.build());
        onChanged();
      } else {
        occupantBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .elevatorService.Occupant occupant = 1;</code>
     */
    public Builder addOccupant(grpc.elevatorService.Occupant value) {
      if (occupantBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureOccupantIsMutable();
        occupant_.add(value);
        onChanged();
      } else {
        occupantBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .elevatorService.Occupant occupant = 1;</code>
     */
    public Builder addOccupant(
        int index, grpc.elevatorService.Occupant value) {
      if (occupantBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureOccupantIsMutable();
        occupant_.add(index, value);
        onChanged();
      } else {
        occupantBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .elevatorService.Occupant occupant = 1;</code>
     */
    public Builder addOccupant(
        grpc.elevatorService.Occupant.Builder builderForValue) {
      if (occupantBuilder_ == null) {
        ensureOccupantIsMutable();
        occupant_.add(builderForValue.build());
        onChanged();
      } else {
        occupantBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .elevatorService.Occupant occupant = 1;</code>
     */
    public Builder addOccupant(
        int index, grpc.elevatorService.Occupant.Builder builderForValue) {
      if (occupantBuilder_ == null) {
        ensureOccupantIsMutable();
        occupant_.add(index, builderForValue.build());
        onChanged();
      } else {
        occupantBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .elevatorService.Occupant occupant = 1;</code>
     */
    public Builder addAllOccupant(
        java.lang.Iterable<? extends grpc.elevatorService.Occupant> values) {
      if (occupantBuilder_ == null) {
        ensureOccupantIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, occupant_);
        onChanged();
      } else {
        occupantBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .elevatorService.Occupant occupant = 1;</code>
     */
    public Builder clearOccupant() {
      if (occupantBuilder_ == null) {
        occupant_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        occupantBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .elevatorService.Occupant occupant = 1;</code>
     */
    public Builder removeOccupant(int index) {
      if (occupantBuilder_ == null) {
        ensureOccupantIsMutable();
        occupant_.remove(index);
        onChanged();
      } else {
        occupantBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .elevatorService.Occupant occupant = 1;</code>
     */
    public grpc.elevatorService.Occupant.Builder getOccupantBuilder(
        int index) {
      return getOccupantFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .elevatorService.Occupant occupant = 1;</code>
     */
    public grpc.elevatorService.OccupantOrBuilder getOccupantOrBuilder(
        int index) {
      if (occupantBuilder_ == null) {
        return occupant_.get(index);  } else {
        return occupantBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .elevatorService.Occupant occupant = 1;</code>
     */
    public java.util.List<? extends grpc.elevatorService.OccupantOrBuilder> 
         getOccupantOrBuilderList() {
      if (occupantBuilder_ != null) {
        return occupantBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(occupant_);
      }
    }
    /**
     * <code>repeated .elevatorService.Occupant occupant = 1;</code>
     */
    public grpc.elevatorService.Occupant.Builder addOccupantBuilder() {
      return getOccupantFieldBuilder().addBuilder(
          grpc.elevatorService.Occupant.getDefaultInstance());
    }
    /**
     * <code>repeated .elevatorService.Occupant occupant = 1;</code>
     */
    public grpc.elevatorService.Occupant.Builder addOccupantBuilder(
        int index) {
      return getOccupantFieldBuilder().addBuilder(
          index, grpc.elevatorService.Occupant.getDefaultInstance());
    }
    /**
     * <code>repeated .elevatorService.Occupant occupant = 1;</code>
     */
    public java.util.List<grpc.elevatorService.Occupant.Builder> 
         getOccupantBuilderList() {
      return getOccupantFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        grpc.elevatorService.Occupant, grpc.elevatorService.Occupant.Builder, grpc.elevatorService.OccupantOrBuilder> 
        getOccupantFieldBuilder() {
      if (occupantBuilder_ == null) {
        occupantBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            grpc.elevatorService.Occupant, grpc.elevatorService.Occupant.Builder, grpc.elevatorService.OccupantOrBuilder>(
                occupant_,
                ((bitField0_ & 0x00000001) == 0x00000001),
                getParentForChildren(),
                isClean());
        occupant_ = null;
      }
      return occupantBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:elevatorService.OccupantDatabase)
  }

  // @@protoc_insertion_point(class_scope:elevatorService.OccupantDatabase)
  private static final grpc.elevatorService.OccupantDatabase DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new grpc.elevatorService.OccupantDatabase();
  }

  public static grpc.elevatorService.OccupantDatabase getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<OccupantDatabase>
      PARSER = new com.google.protobuf.AbstractParser<OccupantDatabase>() {
    @java.lang.Override
    public OccupantDatabase parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new OccupantDatabase(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<OccupantDatabase> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<OccupantDatabase> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public grpc.elevatorService.OccupantDatabase getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

