// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: elevatorService.proto

package grpc.elevatorService;

public interface OccupantOrBuilder extends
    // @@protoc_insertion_point(interface_extends:elevatorService.Occupant)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 id = 1;</code>
   */
  int getId();

  /**
   * <code>string name = 2;</code>
   */
  java.lang.String getName();
  /**
   * <code>string name = 2;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>int32 roomFloor = 3;</code>
   */
  int getRoomFloor();

  /**
   * <code>int32 roomNumber = 4;</code>
   */
  int getRoomNumber();

  /**
   * <code>repeated int32 accessToFloor = 5;</code>
   */
  java.util.List<java.lang.Integer> getAccessToFloorList();
  /**
   * <code>repeated int32 accessToFloor = 5;</code>
   */
  int getAccessToFloorCount();
  /**
   * <code>repeated int32 accessToFloor = 5;</code>
   */
  int getAccessToFloor(int index);
}
