// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: elevatorService.proto

package grpc.elevatorService;

/**
 * <pre>
 *Create the messages
 *Occupant Message to be used in ElevatorRequest message
 * </pre>
 *
 * Protobuf type {@code elevatorService.Occupant}
 */
public  final class Occupant extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:elevatorService.Occupant)
    OccupantOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Occupant.newBuilder() to construct.
  private Occupant(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Occupant() {
    id_ = 0;
    name_ = "";
    roomFloor_ = 0;
    roomNumber_ = 0;
    accessToFloor_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private Occupant(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {

            id_ = input.readInt32();
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            name_ = s;
            break;
          }
          case 24: {

            roomFloor_ = input.readInt32();
            break;
          }
          case 32: {

            roomNumber_ = input.readInt32();
            break;
          }
          case 40: {
            if (!((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
              accessToFloor_ = new java.util.ArrayList<java.lang.Integer>();
              mutable_bitField0_ |= 0x00000010;
            }
            accessToFloor_.add(input.readInt32());
            break;
          }
          case 42: {
            int length = input.readRawVarint32();
            int limit = input.pushLimit(length);
            if (!((mutable_bitField0_ & 0x00000010) == 0x00000010) && input.getBytesUntilLimit() > 0) {
              accessToFloor_ = new java.util.ArrayList<java.lang.Integer>();
              mutable_bitField0_ |= 0x00000010;
            }
            while (input.getBytesUntilLimit() > 0) {
              accessToFloor_.add(input.readInt32());
            }
            input.popLimit(limit);
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
        accessToFloor_ = java.util.Collections.unmodifiableList(accessToFloor_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return grpc.elevatorService.ElevatorServiceImpl.internal_static_elevatorService_Occupant_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return grpc.elevatorService.ElevatorServiceImpl.internal_static_elevatorService_Occupant_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            grpc.elevatorService.Occupant.class, grpc.elevatorService.Occupant.Builder.class);
  }

  private int bitField0_;
  public static final int ID_FIELD_NUMBER = 1;
  private int id_;
  /**
   * <code>int32 id = 1;</code>
   */
  public int getId() {
    return id_;
  }

  public static final int NAME_FIELD_NUMBER = 2;
  private volatile java.lang.Object name_;
  /**
   * <code>string name = 2;</code>
   */
  public java.lang.String getName() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      name_ = s;
      return s;
    }
  }
  /**
   * <code>string name = 2;</code>
   */
  public com.google.protobuf.ByteString
      getNameBytes() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      name_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ROOMFLOOR_FIELD_NUMBER = 3;
  private int roomFloor_;
  /**
   * <code>int32 roomFloor = 3;</code>
   */
  public int getRoomFloor() {
    return roomFloor_;
  }

  public static final int ROOMNUMBER_FIELD_NUMBER = 4;
  private int roomNumber_;
  /**
   * <code>int32 roomNumber = 4;</code>
   */
  public int getRoomNumber() {
    return roomNumber_;
  }

  public static final int ACCESSTOFLOOR_FIELD_NUMBER = 5;
  private java.util.List<java.lang.Integer> accessToFloor_;
  /**
   * <code>repeated int32 accessToFloor = 5;</code>
   */
  public java.util.List<java.lang.Integer>
      getAccessToFloorList() {
    return accessToFloor_;
  }
  /**
   * <code>repeated int32 accessToFloor = 5;</code>
   */
  public int getAccessToFloorCount() {
    return accessToFloor_.size();
  }
  /**
   * <code>repeated int32 accessToFloor = 5;</code>
   */
  public int getAccessToFloor(int index) {
    return accessToFloor_.get(index);
  }
  private int accessToFloorMemoizedSerializedSize = -1;

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    getSerializedSize();
    if (id_ != 0) {
      output.writeInt32(1, id_);
    }
    if (!getNameBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, name_);
    }
    if (roomFloor_ != 0) {
      output.writeInt32(3, roomFloor_);
    }
    if (roomNumber_ != 0) {
      output.writeInt32(4, roomNumber_);
    }
    if (getAccessToFloorList().size() > 0) {
      output.writeUInt32NoTag(42);
      output.writeUInt32NoTag(accessToFloorMemoizedSerializedSize);
    }
    for (int i = 0; i < accessToFloor_.size(); i++) {
      output.writeInt32NoTag(accessToFloor_.get(i));
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (id_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(1, id_);
    }
    if (!getNameBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, name_);
    }
    if (roomFloor_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(3, roomFloor_);
    }
    if (roomNumber_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(4, roomNumber_);
    }
    {
      int dataSize = 0;
      for (int i = 0; i < accessToFloor_.size(); i++) {
        dataSize += com.google.protobuf.CodedOutputStream
          .computeInt32SizeNoTag(accessToFloor_.get(i));
      }
      size += dataSize;
      if (!getAccessToFloorList().isEmpty()) {
        size += 1;
        size += com.google.protobuf.CodedOutputStream
            .computeInt32SizeNoTag(dataSize);
      }
      accessToFloorMemoizedSerializedSize = dataSize;
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof grpc.elevatorService.Occupant)) {
      return super.equals(obj);
    }
    grpc.elevatorService.Occupant other = (grpc.elevatorService.Occupant) obj;

    boolean result = true;
    result = result && (getId()
        == other.getId());
    result = result && getName()
        .equals(other.getName());
    result = result && (getRoomFloor()
        == other.getRoomFloor());
    result = result && (getRoomNumber()
        == other.getRoomNumber());
    result = result && getAccessToFloorList()
        .equals(other.getAccessToFloorList());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + ID_FIELD_NUMBER;
    hash = (53 * hash) + getId();
    hash = (37 * hash) + NAME_FIELD_NUMBER;
    hash = (53 * hash) + getName().hashCode();
    hash = (37 * hash) + ROOMFLOOR_FIELD_NUMBER;
    hash = (53 * hash) + getRoomFloor();
    hash = (37 * hash) + ROOMNUMBER_FIELD_NUMBER;
    hash = (53 * hash) + getRoomNumber();
    if (getAccessToFloorCount() > 0) {
      hash = (37 * hash) + ACCESSTOFLOOR_FIELD_NUMBER;
      hash = (53 * hash) + getAccessToFloorList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static grpc.elevatorService.Occupant parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static grpc.elevatorService.Occupant parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static grpc.elevatorService.Occupant parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static grpc.elevatorService.Occupant parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static grpc.elevatorService.Occupant parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static grpc.elevatorService.Occupant parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static grpc.elevatorService.Occupant parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static grpc.elevatorService.Occupant parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static grpc.elevatorService.Occupant parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static grpc.elevatorService.Occupant parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static grpc.elevatorService.Occupant parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static grpc.elevatorService.Occupant parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(grpc.elevatorService.Occupant prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   *Create the messages
   *Occupant Message to be used in ElevatorRequest message
   * </pre>
   *
   * Protobuf type {@code elevatorService.Occupant}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:elevatorService.Occupant)
      grpc.elevatorService.OccupantOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return grpc.elevatorService.ElevatorServiceImpl.internal_static_elevatorService_Occupant_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return grpc.elevatorService.ElevatorServiceImpl.internal_static_elevatorService_Occupant_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              grpc.elevatorService.Occupant.class, grpc.elevatorService.Occupant.Builder.class);
    }

    // Construct using grpc.elevatorService.Occupant.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      id_ = 0;

      name_ = "";

      roomFloor_ = 0;

      roomNumber_ = 0;

      accessToFloor_ = java.util.Collections.emptyList();
      bitField0_ = (bitField0_ & ~0x00000010);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return grpc.elevatorService.ElevatorServiceImpl.internal_static_elevatorService_Occupant_descriptor;
    }

    @java.lang.Override
    public grpc.elevatorService.Occupant getDefaultInstanceForType() {
      return grpc.elevatorService.Occupant.getDefaultInstance();
    }

    @java.lang.Override
    public grpc.elevatorService.Occupant build() {
      grpc.elevatorService.Occupant result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public grpc.elevatorService.Occupant buildPartial() {
      grpc.elevatorService.Occupant result = new grpc.elevatorService.Occupant(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      result.id_ = id_;
      result.name_ = name_;
      result.roomFloor_ = roomFloor_;
      result.roomNumber_ = roomNumber_;
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        accessToFloor_ = java.util.Collections.unmodifiableList(accessToFloor_);
        bitField0_ = (bitField0_ & ~0x00000010);
      }
      result.accessToFloor_ = accessToFloor_;
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof grpc.elevatorService.Occupant) {
        return mergeFrom((grpc.elevatorService.Occupant)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(grpc.elevatorService.Occupant other) {
      if (other == grpc.elevatorService.Occupant.getDefaultInstance()) return this;
      if (other.getId() != 0) {
        setId(other.getId());
      }
      if (!other.getName().isEmpty()) {
        name_ = other.name_;
        onChanged();
      }
      if (other.getRoomFloor() != 0) {
        setRoomFloor(other.getRoomFloor());
      }
      if (other.getRoomNumber() != 0) {
        setRoomNumber(other.getRoomNumber());
      }
      if (!other.accessToFloor_.isEmpty()) {
        if (accessToFloor_.isEmpty()) {
          accessToFloor_ = other.accessToFloor_;
          bitField0_ = (bitField0_ & ~0x00000010);
        } else {
          ensureAccessToFloorIsMutable();
          accessToFloor_.addAll(other.accessToFloor_);
        }
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      grpc.elevatorService.Occupant parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (grpc.elevatorService.Occupant) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private int id_ ;
    /**
     * <code>int32 id = 1;</code>
     */
    public int getId() {
      return id_;
    }
    /**
     * <code>int32 id = 1;</code>
     */
    public Builder setId(int value) {
      
      id_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 id = 1;</code>
     */
    public Builder clearId() {
      
      id_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object name_ = "";
    /**
     * <code>string name = 2;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string name = 2;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string name = 2;</code>
     */
    public Builder setName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      name_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string name = 2;</code>
     */
    public Builder clearName() {
      
      name_ = getDefaultInstance().getName();
      onChanged();
      return this;
    }
    /**
     * <code>string name = 2;</code>
     */
    public Builder setNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      name_ = value;
      onChanged();
      return this;
    }

    private int roomFloor_ ;
    /**
     * <code>int32 roomFloor = 3;</code>
     */
    public int getRoomFloor() {
      return roomFloor_;
    }
    /**
     * <code>int32 roomFloor = 3;</code>
     */
    public Builder setRoomFloor(int value) {
      
      roomFloor_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 roomFloor = 3;</code>
     */
    public Builder clearRoomFloor() {
      
      roomFloor_ = 0;
      onChanged();
      return this;
    }

    private int roomNumber_ ;
    /**
     * <code>int32 roomNumber = 4;</code>
     */
    public int getRoomNumber() {
      return roomNumber_;
    }
    /**
     * <code>int32 roomNumber = 4;</code>
     */
    public Builder setRoomNumber(int value) {
      
      roomNumber_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 roomNumber = 4;</code>
     */
    public Builder clearRoomNumber() {
      
      roomNumber_ = 0;
      onChanged();
      return this;
    }

    private java.util.List<java.lang.Integer> accessToFloor_ = java.util.Collections.emptyList();
    private void ensureAccessToFloorIsMutable() {
      if (!((bitField0_ & 0x00000010) == 0x00000010)) {
        accessToFloor_ = new java.util.ArrayList<java.lang.Integer>(accessToFloor_);
        bitField0_ |= 0x00000010;
       }
    }
    /**
     * <code>repeated int32 accessToFloor = 5;</code>
     */
    public java.util.List<java.lang.Integer>
        getAccessToFloorList() {
      return java.util.Collections.unmodifiableList(accessToFloor_);
    }
    /**
     * <code>repeated int32 accessToFloor = 5;</code>
     */
    public int getAccessToFloorCount() {
      return accessToFloor_.size();
    }
    /**
     * <code>repeated int32 accessToFloor = 5;</code>
     */
    public int getAccessToFloor(int index) {
      return accessToFloor_.get(index);
    }
    /**
     * <code>repeated int32 accessToFloor = 5;</code>
     */
    public Builder setAccessToFloor(
        int index, int value) {
      ensureAccessToFloorIsMutable();
      accessToFloor_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated int32 accessToFloor = 5;</code>
     */
    public Builder addAccessToFloor(int value) {
      ensureAccessToFloorIsMutable();
      accessToFloor_.add(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated int32 accessToFloor = 5;</code>
     */
    public Builder addAllAccessToFloor(
        java.lang.Iterable<? extends java.lang.Integer> values) {
      ensureAccessToFloorIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, accessToFloor_);
      onChanged();
      return this;
    }
    /**
     * <code>repeated int32 accessToFloor = 5;</code>
     */
    public Builder clearAccessToFloor() {
      accessToFloor_ = java.util.Collections.emptyList();
      bitField0_ = (bitField0_ & ~0x00000010);
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:elevatorService.Occupant)
  }

  // @@protoc_insertion_point(class_scope:elevatorService.Occupant)
  private static final grpc.elevatorService.Occupant DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new grpc.elevatorService.Occupant();
  }

  public static grpc.elevatorService.Occupant getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Occupant>
      PARSER = new com.google.protobuf.AbstractParser<Occupant>() {
    @java.lang.Override
    public Occupant parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new Occupant(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Occupant> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Occupant> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public grpc.elevatorService.Occupant getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

