// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: lightingService.proto

package grpc.lightingService;

public interface LightingResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:lightingService.LightingResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 brightnessValue = 1;</code>
   */
  int getBrightnessValue();

  /**
   * <code>string lightingMessage = 2;</code>
   */
  java.lang.String getLightingMessage();
  /**
   * <code>string lightingMessage = 2;</code>
   */
  com.google.protobuf.ByteString
      getLightingMessageBytes();
}
