// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: lightingService.proto

package grpc.lightingService;

public interface RoomOrBuilder extends
    // @@protoc_insertion_point(interface_extends:lightingService.Room)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 id = 1;</code>
   */
  int getId();

  /**
   * <code>string roomName = 2;</code>
   */
  java.lang.String getRoomName();
  /**
   * <code>string roomName = 2;</code>
   */
  com.google.protobuf.ByteString
      getRoomNameBytes();

  /**
   * <code>int32 brightness = 3;</code>
   */
  int getBrightness();

  /**
   * <code>int32 blindDrawnAmount = 4;</code>
   */
  int getBlindDrawnAmount();

  /**
   * <code>double temperature = 5;</code>
   */
  double getTemperature();
}
