// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: occupantService.proto

package grpc.occupantService;

public interface EmptyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:occupantService.Empty)
    com.google.protobuf.MessageOrBuilder {
}
