// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: occupantService.proto

package grpc.occupantService;

public interface GymTrainerOrBuilder extends
    // @@protoc_insertion_point(interface_extends:occupantService.GymTrainer)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 id = 1;</code>
   */
  int getId();

  /**
   * <code>string name = 2;</code>
   */
  java.lang.String getName();
  /**
   * <code>string name = 2;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>string speciality = 3;</code>
   */
  java.lang.String getSpeciality();
  /**
   * <code>string speciality = 3;</code>
   */
  com.google.protobuf.ByteString
      getSpecialityBytes();

  /**
   * <code>bool availableNow = 4;</code>
   */
  boolean getAvailableNow();

  /**
   * <code>.occupantService.Time nextAvailableTime = 5;</code>
   */
  boolean hasNextAvailableTime();
  /**
   * <code>.occupantService.Time nextAvailableTime = 5;</code>
   */
  grpc.occupantService.Time getNextAvailableTime();
  /**
   * <code>.occupantService.Time nextAvailableTime = 5;</code>
   */
  grpc.occupantService.TimeOrBuilder getNextAvailableTimeOrBuilder();
}
