// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: occupantService.proto

package grpc.occupantService;

public final class occupantServiceImpl {
  private occupantServiceImpl() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_occupantService_Empty_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_occupantService_Empty_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_occupantService_GymTrainer_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_occupantService_GymTrainer_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_occupantService_Time_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_occupantService_Time_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\025occupantService.proto\022\017occupantService" +
      "\"\007\n\005Empty\"\246\001\n\nGymTrainer\022\n\n\002id\030\001 \001(\005\022\014\n\004" +
      "name\030\002 \001(\t\022\022\n\nspeciality\030\003 \001(\t\022\023\n\013phoneN" +
      "umber\030\004 \001(\t\022\r\n\005email\030\005 \001(\t\022\024\n\014availableN" +
      "ow\030\006 \001(\010\0220\n\021nextAvailableTime\030\007 \001(\0132\025.oc" +
      "cupantService.Time\"$\n\004Time\022\014\n\004hour\030\001 \001(\005" +
      "\022\016\n\006minute\030\002 \001(\0052]\n\017occupantService\022J\n\017v" +
      "iewGymTrainers\022\026.occupantService.Empty\032\033" +
      ".occupantService.GymTrainer\"\0000\001B-\n\024grpc." +
      "occupantServiceB\023occupantServiceImplP\001b\006" +
      "proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_occupantService_Empty_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_occupantService_Empty_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_occupantService_Empty_descriptor,
        new java.lang.String[] { });
    internal_static_occupantService_GymTrainer_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_occupantService_GymTrainer_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_occupantService_GymTrainer_descriptor,
        new java.lang.String[] { "Id", "Name", "Speciality", "PhoneNumber", "Email", "AvailableNow", "NextAvailableTime", });
    internal_static_occupantService_Time_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_occupantService_Time_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_occupantService_Time_descriptor,
        new java.lang.String[] { "Hour", "Minute", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
