// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: occupantService.proto

package grpc.occupantService;

public interface TimeOrBuilder extends
    // @@protoc_insertion_point(interface_extends:occupantService.Time)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 hour = 1;</code>
   */
  int getHour();

  /**
   * <code>int32 minute = 2;</code>
   */
  int getMinute();
}
